language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1           # automatically the latest version to this major
  - nightly
sudo: required
codecov: true
git:
  depth: 3 
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
  webhooks: https://www.travisbuddy.com
  on_success: never
